name: pr
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  packages: read    # Needed for npm and container registry
  actions: read
jobs:
  pr_validation:
    uses: montara-io/ci_workflows/.github/workflows/pr.yml@main
    secrets:
      WORKFLOW_ACTION_TOKEN: ${{ secrets.WORKFLOW_ACTION_TOKEN }}
